<p> ::= <pn>(<pinput>)
<pn> ::= PA 
        | PS 
        | PM 
        | PD
<pinput> ::= [<winput>,<winput>]
        | [<winput>,<winput>,<winput>]
        | [<winput>,<winput>,<winput>,<winput>]
        | [<winput>,<winput>,<winput>,<winput>,<winput>]
<winput> ::= (<cop> * <v>)
        | (<cop> * <p>)
<cop> ::= float(<num>)
        | <e>
<e>   ::= (<cop> + <cop>)
        | (<cop> - <cop>)
        | (<cop> * <cop>)
        | pdiv(<cop>,<cop>)
<num> ::= <dig>.<dig>
        | .<dig>
        | .<dig><dig>
        | <dig>.<dig><dig>
        | <dig><dig>.<dig><dig>
<dig> ::= 0
        | 1
        | 2
        | 3
        | 4
        | 5
        | 6
        | 7
        | 8
        | 9
<v> ::= x[0] | x[1] | x[2] | x[3] | x[4] | x[5] | x[6] | x[7] | x[8] | x[9]
